steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/bolt-app:${SHORT_SHA}', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/bolt-app']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'bolt-app', '--image', 'gcr.io/$PROJECT_ID/bolt-app:${SHORT_SHA}', '--memory', '1Gi', '--region', 'asia-northeast1', '--platform', 'managed', '--allow-unauthenticated', '--update-env-vars', 'NODE_ENV=production,SLACK_SIGNING_SECRET=${_SLACK_SIGNING_SECRET},SLACK_CLIENT_ID=${_SLACK_CLIENT_ID},SLACK_CLIENT_SECRET=${_SLACK_CLIENT_SECRET},DATASTORE_PROJECT_ID=$PROJECT_ID']
images:
- gcr.io/$PROJECT_ID/bolt-app
